# Generated by Django 5.2 on 2025-07-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Ville')),
                ('site', models.CharField(max_length=255, verbose_name='Emplacement ou URL')),
                ('description', models.TextField()),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='main.pays')),
            ],
        ),
    ]
