# Generated by Django 5.2 on 2025-07-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='prix_par_nuit',
            new_name='prix_par_nuit_moyen',
        ),
    ]
