# Generated by Django 5.2 on 2025-07-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pays_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=255)),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('type', models.CharField(choices=[('hotel', 'Hôtel'), ('auberge', 'Auberge'), ('bnb', 'B&B'), ('camping', 'Camping'), ('autre', 'Autre')], default='hotel', max_length=50)),
                ('capacite', models.PositiveIntegerField(help_text='Nombre de personnes maximum')),
                ('site_web', models.URLField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hebergements', to='main.destination')),
            ],
        ),
    ]
