# Generated by Django 5.2 on 2025-07-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hebergement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergement',
            name='site_web',
        ),
    ]
