# Generated by Django 5.2 on 2025-07-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_hebergement_site_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='sejour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Séjour'),
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hebergements', models.ManyToManyField(related_name='sejours', to='main.hebergement')),
            ],
        ),
    ]
