# Generated by Django 5.2 on 2025-07-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_destination_sejour_sejour'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='eco_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Éco-label'),
        ),
    ]
