# Generated by Django 5.2 on 2025-07-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_destination_eco_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergement',
            name='capacite',
        ),
        migrations.AddField(
            model_name='hebergement',
            name='chambre_3p',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de chambres 3 personnes'),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='chambre_4p',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de chambres 4 personnes'),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='chambre_5p',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de chambres 5 personnes'),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='prix_3p',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix par nuit pour une chambre 3 personnes', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='prix_4p',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix par nuit pour une chambre 4 personnes', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='prix_5p',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix par nuit pour une chambre 5 personnes', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='prix_studio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix par nuit pour un studio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='studio',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de studios'),
        ),
    ]
