# Generated by Django 5.2 on 2025-07-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_hebergement_capacite_hebergement_chambre_3p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergement',
            name='eco_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Éco-label'),
        ),
    ]
