# Generated by Django 5.2 on 2025-07-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paye',
            field=models.BooleanField(default=False),
        ),
    ]
