# Generated by Django 5.2 on 2025-07-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reservation_paye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_edition', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('conseils', 'Conseils'), ('destinations', 'Destinations'), ('ecologie', 'Écologie'), ('actualites', 'Actualités')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog_photos/')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='main.utilisateur')),
            ],
        ),
    ]
