# Generated by Django 5.2 on 2025-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='destination_photos/'),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hebergement_photos/'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='evaluation',
            field=models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★'), (3, '★'), (4, '★'), (5, '★')], default=5),
        ),
    ]
